[nematic_system_mpi_driver]
input_archive_filename = ""
perturbation_archive_filename = ""
starting_timestep = 1

	[nematic_system_mpi_driver.file_output]
	checkpoint_interval = 1
	vtu_interval = 1
	data_folder = "/home/lucas/Documents/research/maier-saupe-lc-hydrodynamics/temp-data/debugging-L3-term/periodic-director-perturbation/"
	archive_filename = "/home/lucas/Documents/research/maier-saupe-lc-hydrodynamics/temp-data/debugging-L3-term/periodic-director-perturbation/nematic_configuration"
	configuration_filename = "nematic_configuration"
	defect_filename = "defect_positions"
	energy_filename = "configuration_energy"
	
	[nematic_system_mpi_driver.defect_detection]
	defect_size = 2.0
	defect_charge_threshold = 0.1
	
	[nematic_system_mpi_driver.grid]
	grid_type = "hyper_cube"
	grid_arguments = "-1.5707963267948 : 1.5707963267948 : false"
	left = -1.5707963267948
	right = 1.5707963267948
	number_of_refines = 8
	number_of_further_refines = 0
	defect_refine_distances  = []
	defect_position = 0.0
	defect_radius = 10.0
	outer_radius = 5.0
	
	[nematic_system_mpi_driver.simulation]
	finite_element_degree = 1
	time_discretization = "semi_implicit"
	theta = 0.5
	dt = 0.1
	number_of_steps = 1
	simulation_tolerance = 1e-10
	simulation_newton_step = 1.0
	simulation_maximum_iterations = 100
	freeze_defects = false

[nematic_system_mpi]

	[nematic_system_mpi.field_theory]
	field_theory = "MS"
	L2 = 0.0
	L3 = 0.0
	
		[nematic_system_mpi.field_theory.maier_saupe]
		maier_saupe_alpha = 8.0
		lebedev_order = 974
		lagrange_step_size = 1.0
		lagrange_tolerance = 1e-10
		lagrange_maximum_iterations = 100
		
		[nematic_system_mpi.field_theory.landau_de_gennes]
		A = -0.064
		B = -1.57
		C = 1.29
	
	[nematic_system_mpi.boundary_values]
	name = "periodic"
	boundary_condition = "Neumann"
	S_value = 0.6751
	
		[nematic_system_mpi.boundary_values.defect_configurations]
		defect_positions = [[0.0, 0.0]]
		defect_charges = [0.5]
		defect_orientations = [0.0]
		defect_radius = 3.0
		defect_charge_name = "plus-half"
		
		[nematic_system_mpi.boundary_values.dzyaloshinskii]
		anisotropy_eps = 0.0
		degree = 1
		charge = 0.5
		n_refines = 10
		tol = 1e-10
		max_iter = 100
		newton_step = 1.0
		
		[nematic_system_mpi.boundary_values.periodic_configurations]
		phi = 0.0
		k = 1.0
		eps = 0.1
		
		[nematic_system_mpi.boundary_values.perturbative_two_defect]
		defect_distance = 50.0
		defect_position_name = "left"
		defect_isomorph_name = "a"
	
	[nematic_system_mpi.initial_values]
	
		[nematic_system_mpi.initial_values.boundary_values]
		name = "periodic"
		boundary_condition = "Neumann"
		S_value = 0.6751
		
			[nematic_system_mpi.initial_values.boundary_values.defect_configurations]
			defect_positions = [[0.0, 0.0]]
			defect_charges = [0.5]
			defect_orientations = [0.0]
			defect_radius = 3.0
			defect_charge_name = "plus-half"
			
			[nematic_system_mpi.initial_values.boundary_values.dzyaloshinskii]
			anisotropy_eps = 0.0
			degree = 1
			charge = 0.5
			n_refines = 10
			tol = 1e-10
			max_iter = 100
			newton_step = 1.0
			
			[nematic_system_mpi.initial_values.boundary_values.periodic_configurations]
			phi = 0.0
			k   = 1.0
			eps = 0.1
			
			[nematic_system_mpi.initial_values.boundary_values.perturbative_two_defect]
			defect_distance = 50.0
			defect_position_name = "left"
			defect_isomorph_name = "a"
	
		[nematic_system_mpi.internal_boundary_values.left.boundary_values]
		name = "two-defect"
		boundary_condition = "Dirichlet"
		S_value = 0.6751
		
			[nematic_system_mpi.internal_boundary_values.left.boundary_values.defect_configurations]
			defect_positions = [[-30.0, 0.0], [30.0, 0.0]]
			defect_charges = [0.5, -0.5]
			defect_orientations = [0.5]
			defect_radius = 3.0
			defect_charge_name = "plus-half-minus-half-alt"
			
			[nematic_system_mpi.internal_boundary_values.left.boundary_values.dzyaloshinskii]
			anisotropy_eps = 0.0
			degree = 1
			charge = 0.5
			n_refines = 10
			tol = 1e-10
			max_iter = 100
			newton_step = 1.0
			
			[nematic_system_mpi.internal_boundary_values.left.boundary_values.periodic_configurations]
			phi = 0.0
			k = 1.0
			eps = 0.1
			
			[nematic_system_mpi.internal_boundary_values.left.boundary_values.perturbative_two_defect]
			defect_distance = 20.0
			defect_position_name = "left"
			defect_isomorph_name = "a"
	
		[nematic_system_mpi.internal_boundary_values.right.boundary_values]
		name = "two-defect"
		boundary_condition = "Dirichlet"
		S_value = 0.6751
		
			[nematic_system_mpi.internal_boundary_values.right.boundary_values.defect_configurations]
			defect_positions = [[-30.0, 0.0], [30.0, 0.0]]
			defect_charges = [0.5, -0.5]
			defect_orientations = [0.5]
			defect_radius = 3.0
			defect_charge_name  = "plus-half-minus-half-alt"
			
			[nematic_system_mpi.internal_boundary_values.right.boundary_values.dzyaloshinskii]
			anisotropy_eps = 0.0
			degree = 1
			charge = 0.5
			n_refines = 10
			tol = 1e-10
			max_iter = 100
			newton_step = 1.0
			
			[nematic_system_mpi.internal_boundary_values.right.boundary_values.periodic_configurations]
			phi = 0.0
			k   = 1.0
			eps = 0.1
			
			[nematic_system_mpi.internal_boundary_values.right.boundary_values.perturbative_two_defect]
			defect_distance = 20.0
			defect_position_name = "right"
			defect_isomorph_name = "a"
