"""
This script reads data from hdf5 generated by `two_defect_fourier_modes.py`
generates azimuthal Fourier mode data at several radial distances, and then
plots several metrics associated with the Fourier data.
"""
import argparse



def get_commandline_args():
    
    description = ('Reads Q-component hdf5 data generated by '
                   '`two_defect_fourier_modes.py` and computes azimuthal '
                   'Fourier modes at many radial distances, and then plots '
                   'various metrics computable from the Fourier modes')

    parser = argparse.ArgumentParser(description=description)
    parser.add_argument('--data_folder',
                        dest='data_folder',
                        help='folder where hdf5 Q-component data lives')
    parser.add_argument('--filename',
                        dest='filename',
                        help='name of hdf5 file holding Q-component data')



def main():

    print("hello")



if __name__ == "__main__":
    main()
